### ISSUE TITLE
Clean UP & Dockerization eos9yy1

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos9yy1#12]
Please refactor this model to work with the latest structure of the template

**Comment by samuelmaina** [comment]
@GemmaTuron  made a PR on it. Have  a look.

**Comment by samuelmaina** [comment]
@GemmaTuron , made  a PR on the model. Was able to fetch and predict the eml_canonical.csv 
[eos9yy1_fetch_cli.log](https://github.com/ersilia-os/eos9yy1/files/11787326/eos9yy1_fetch_cli.log)
[eos9yy1_cli_eml_pred.csv](https://github.com/ersilia-os/eos9yy1/files/11787328/eos9yy1_cli_eml_pred.csv)

**Comment by samuelmaina** [comment]
Have seen the model upload fails with sklearn for ARM 64, I am working on the that.

**Comment by samuelmaina** [comment]
@GemmaTuron, Have made a PR

**Comment by samuelmaina** [comment]
@GemmaTuron , The change made works for AMD and ARM . The two tags are in Airtable as well

**Comment by GemmaTuron** [comment]
great work @samuelmaina, thanks!
We can close this issue then!
