### ISSUE TITLE
Testing model eos9yy1

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos9yy1#2]
This model is ready for testing!

**Comment by carcablop** [comment]
Hello @GemmaTuron .
This model fails to fetch in the CLI and in Google Colab.
This is the fetch log. 
[log_fetch_eos9yy1.txt](https://github.com/ersilia-os/eos9yy1/files/10872355/log_fetch_eos9yy1.txt)

The error it is giving because no value has been set for the Input Shape field. This means that in the metadata.json the Input Shape field is empty.
Taking a look at the metadata.json there are missing fields to fill in.

**Comment by GemmaTuron** [comment]
Yes I've realized the metadata has not been properly updated and pointed @pauline-banye to change it
It's because the slug was changed after the model was already listed in airtable. 

sorry I didnt let you know earlier, waith for the edit from Pauline please

**Comment by GemmaTuron** [comment]
@carcablop can you try that again? I've updated everything

**Comment by Femme-js** [comment]
Hi @GemmaTuron !

I tested this model on my CLI and Colab. It is working fine on my Colab. 

But on my CLI, it is giving the following error. 
https://colab.research.google.com/drive/11MF2tQMwnRS7fC3eZ7snjNIsHYsSxqOO?usp=sharing

```
File "/home/femme_js/miniconda3/envs/ersilia/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 383, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for ersilia
```
I can see that metadata file is still not able to provide the package information, I guess.

**Comment by GemmaTuron** [comment]
Hi @Femme-js 
Thanks for testing! If the model is working in colab, the metadata is there, otherwise you would not be able to fetch it. Can you please provide the full log file for the error above? Otherwise it is difficult to understand what might be going on

**Comment by carcablop** [comment]
Hi @GemmaTuron 
The model fetch sucessfully in my CLI and Colab. 
This is the log fetch : [log_fetch_eos9yy1.txt](https://github.com/ersilia-os/eos9yy1/files/11030999/log_fetch_eos9yy1.txt)

This is the ouput with eml_canonical input file: 
[out_eos9yy1.csv](https://github.com/ersilia-os/eos9yy1/files/11031020/out_eos9yy1.csv)

This is the output when run with one molecule and try to save in a .csv file.  This produces an error when I try to write to a .csv file: 
[output_one_mol_eos9yy1.txt](https://github.com/ersilia-os/eos9yy1/files/11031056/output_one_mol_eos9yy1.txt)

I think that this is not a problem of the model, if I print in the console it produces an output. In Google colab it does not give any error.
But if I go back and fetch the model and go back and run the predictions for a molecule and try to save it to a .csv file it doesn't give an error. I attach the file: [output_onemol_eos9yy1_2.csv](https://github.com/ersilia-os/eos9yy1/files/11031328/output_onemol_eos9yy1_2.csv)
 But then I try to run it for the whole eml_canonical and get the same error above.
It's a strange behavior, I think it may be with the output adapter with ersilia and not with the model. It only happens in the CLI and not in Colab. Let me debug a bit more on this.

**Comment by GemmaTuron** [comment]
Hi @carcablop !

Thanks for checking, indeed it seems that the input and output adaptors in the model are not right. Does it also happen with other NCATs models, like the eos81ew?
